### ISSUE TITLE
Terraform v0.14 support?

### ISSUE THREAD

**Issue by yamaszone** [terraform-google-modules/terraform-google-cloud-router#18]
Looking at https://github.com/terraform-google-modules/terraform-google-cloud-router/pull/17 from @bharathkkb it felt like, this module may support Terraform `v0.14.x` but running into following during `terraform plan`:

```
Error: Unsupported Terraform Core version

  on .terraform/modules/cloud_router/versions.tf line 18, in terraform:
  18:   required_version = ">=0.12, <0.14"

Module module.cloud_router (from
terraform-google-modules/cloud-router/google) does not support Terraform
version 0.14.2. To proceed, either choose another supported Terraform version
or update this version constraint. Version constraints are normally set for
good reason, so updating the constraint may lead to other errors or unexpected
behavior.
```

Weirdly I didn't see this error when ran `terraform plan` against `example/nat/` of this repo. Any comment on if this module is expected to support `v0.14`? If not, any ETA?

**Comment by bharathkkb** [comment]
Hi @yamaszone 
That seems odd, it should have said something during `terraform init` if we missed a constraint. 
Is the source still `source = "../../"`? We have not released a new version with the relaxed constraint to the registry yet.

**Comment by yamaszone** [comment]
@bharathkkb thanks for responding promptly! I was initially trying `version = "= 0.3.0"` with `source` as
```
  source = "terraform-google-modules/cloud-router/google"
  version = "= 0.3.0"
```
but realized the new version was not released yet. Then I removed `version = "= 0.3.0"` hoping the branch `master` will be imported but that was not the case.
```
  source = "terraform-google-modules/cloud-router/google"
```

I was able to workaround the issue by switching the module `source` to
```
  source = "git@github.com:terraform-google-modules/terraform-google-cloud-router.git"
```

Can you please create a new release tag from `master` to allow version pinning? Thanks for your help!

**Comment by chenglanguo** [comment]
same issue

**Comment by bharathkkb** [comment]
@yamaszone @chenglanguo `v0.4.0` has been released with that patch
