### ISSUE TITLE
Optional log_config block for nat

### ISSUE THREAD

**Issue by s1mark** [terraform-google-modules/terraform-google-cloud-router#26]
It would be nice to have this optional

https://github.com/terraform-google-modules/terraform-google-cloud-router/blob/2154aee587cf302cb583b1334f52f923b1801477/nat.tf#L37-L40

Maybe a simple enhancement like so:

```terraform
  log_config {
    enable = lookup(lookup(each.value, "log_config", {}), "enable", true)
    filter = lookup(lookup(each.value, "log_config", {}), "filter", "ALL")
  }
```

Probably it would be more elegant to be able to drop the whole `log_config{}` with some `dynamic{}` block logic

**Comment by aoshfan** [comment]
Hi, will this add an optiona to disable the log ? Currently i'm using `Simple Cloud Router`.

Thank you.

**Comment by brahama** [comment]
Yes, I agree. A simple option to make it possible to disable. Why would we want to have this hardcoded to enable? I assume also this incurs in costs that might not we wanted for some environments.

**Comment by voxmaster** [comment]
Can someone reopen the PR above? That will fix the issue.
