### ISSUE TITLE
Support MTU attribute for google_compute_interconnect_attachment

### ISSUE THREAD

**Issue by steffencircle** [terraform-google-modules/terraform-google-cloud-router#28]
Hi,

the underlying resource google_compute_interconnect_attachment supports the attribute for "mtu".
This should also be possible to specify via the module.

**Comment by bharathkkb** [comment]
Hi @steffencircle 
Happy to review a PR for this

**Comment by steffencircle** [comment]
Cool 👍 
Here you go:
https://github.com/terraform-google-modules/terraform-google-cloud-router/pull/29
