### ISSUE TITLE
Support Google provider 4.0

### ISSUE THREAD

**Issue by jackwhelpton** [terraform-google-modules/terraform-google-cloud-router#37]
### TL;DR

Because the current module constrains the Google provider to `version ~> 3.0`, it can't be used in conjunction with other modules that require `version >= 4.0`.

### Expected behavior

Module is usable with Google provider 4.0.

### Terraform Configuration

```hcl
Could not retrieve the list of available versions for provider hashicorp/google: no available releases match the
│ given constraints >= 2.12.0, >= 3.43.0, >= 3.45.0, ~> 3.53, >= 4.0.0, < 4.0.0, < 5.0.0
```

### Terraform Version

```sh
Terraform v1.0.9
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v3.90.1
+ provider registry.terraform.io/hashicorp/google-beta v3.90.1
```

### Additional information

There appears to be an automated PR raised for this, but it may have problems:

https://github.com/terraform-google-modules/terraform-google-cloud-router/pull/36

Raising this issue just to make sure there's a set of eyes on that.

**Comment by bharathkkb** [comment]
Thanks for the report @jackwhelpton. Looks like the automation missed a file due to different file name. I fixed that and merged https://github.com/terraform-google-modules/terraform-google-cloud-router/pull/36
