### ISSUE TITLE
Properties are not documented well

### ISSUE THREAD

**Issue by j-windsor** [terraform-google-modules/terraform-google-cloud-router#50]
Several properties on this module are not documented well. An example is `bgp`: an unexplained acronym with an `any` type. I have no information about this property.

Please improve documentation so users don't have to fish through the implementation to determine how to set properties.

**Comment by bharathkkb** [comment]
Similar to https://github.com/terraform-google-modules/terraform-google-lb-http/issues/271#issuecomment-1297816489
Currently some documented in https://github.com/terraform-google-modules/terraform-google-cloud-router/blob/65b204bc5ac1501f38d41141c773afefc0d25c3a/variables.tf#L47-L53
