### ISSUE TITLE
partner interconnect not supported

### ISSUE THREAD

**Issue by arctiqaurora** [terraform-google-modules/terraform-google-cloud-router#7]
For partner interconnect, variable `interconnect` is not allowed in terraform. However this module variable `interconnect` is required regardless of interconnect type.

For partner interconnect, variable `edge_availability_domain` should be required, but it is not part of the module yet.

**Comment by morgante** [comment]
Yes, currently only dedicated interconnects are supported. I'm happy to review a pull request adding support for partner interconnects (potentially as a separate submodule).

**Comment by rnfawcett** [comment]
@arctiqaurora is correct.  However, if you set `interconnect` to an empty string, the result is
- `terraform apply` results in an error
- the resultant partner connection that's created appears to be just fine

**Comment by CrackerJackMack** [comment]
can this be reopened please?  These are great blueprints. Just need some polish here and there.

**Comment by CrackerJackMack** [comment]
One thing I've found, and maybe it's user error, is that when using a partner interconnect w/o this blueprint it auto-creates BGP sessions such as `auto-ia-bgp-.....` where as I don't get these BGP peering sessions using dedicated attachements and have to use `google_compute_router_interface` and `google_compute_router_peer`

Related? https://github.com/hashicorp/terraform-provider-google/issues/11560
If the answer is "just import it!" that's dumb and not very terraform like.

```
resource "google_compute_interconnect_attachment" "on_prem_0" {
  project                  = var.project_id
  name                     = "${var.name_prefix}-${var.region}-0"
  edge_availability_domain = "AVAILABILITY_DOMAIN_1"
  type                     = "PARTNER"
  router                   = var.router
  mtu                      = var.mtu
  region                   = var.region
}

resource "packetfabric_cloud_router_connection_google" "onramp_0" {
  provider                    = packetfabric
  description                 = google_compute_interconnect_attachment.on_prem_0.name
  google_vlan_attachment_name = google_compute_interconnect_attachment.on_prem_0.name
  circuit_id                  = var.pf_cloud_router_id
  google_pairing_key          = google_compute_interconnect_attachment.on_prem_0.pairing_key
  pop                         = var.pf_pop
  speed                       = var.speed
  maybe_nat                   = false
  labels                      = ["terraform"]
}
```
